# Generated by Django 6.0.2 on 2026-04-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_dailyattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
